# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-17 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default=1000, max_length=1000),
            preserve_default=False,
        ),
    ]
