# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-15 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default=510, max_length=510),
            preserve_default=False,
        ),
    ]
