# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-15 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_dojos_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='desc',
            field=models.TextField(),
        ),
    ]
